### 
### model
model_name_or_path: /media/zzcc/file/aigc/llm/models/Qwen/Qwen2___5-VL-3B-Instruct
adapter_name_or_path: saves/Qwen2.5-VL-3B-Instruct/lora/train_2025-10-10-23-25-08
template: qwen2_vl
finetuning_type: lora

### export
export_dir: ../models/Qwen/Qwen2.5-VL-3B-Instruct-finetune-tiny
export_size: 2
export_device: auto
export_legacy_format: false