bf16: true
cutoff_len: 2048
dataset: tusimple_llamafactory_tiny
dataset_dir: /media/zzcc/file/aigc/llm/lane_detection/llama_factory_finetune
ddp_timeout: 180000000
do_train: true
enable_thinking: true
finetuning_type: lora
flash_attn: auto
freeze_multi_modal_projector: true
freeze_vision_tower: true
gradient_accumulation_steps: 16
image_max_pixels: 2073600
image_min_pixels: 1024
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: /media/zzcc/file/aigc/llm/models/Qwen/Qwen2___5-VL-3B-Instruct/
num_train_epochs: 2.0
optim: adamw_torch
output_dir: saves/Qwen2.5-VL-3B-Instruct/lora/train_2025-10-10-00-08-46
packing: false
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: qwen2_vl
trust_remote_code: true
video_max_pixels: 65536
video_min_pixels: 256
warmup_steps: 0
